sudo: false
dist: trusty

language: python

services:
  - docker

before_install:
  - docker pull ubuntu:xenial
  - docker run -d --name NRMC2019-CI -v $(pwd):/NRMC2019 ubuntu:xenial tail -f /dev/null
  - docker ps
  - docker exec -t NRMC2019-CI bash -c "
    useradd -ms /bin/bash travis;
    apt-get update;
    apt-get install sudo"
  - 'docker exec -t NRMC2019-CI bash -c "echo travis ALL=\(ALL\) NOPASSWD: ALL >> /etc/sudoers"'

install:
  - docker exec -u travis -t NRMC2019-CI bash -c "
    sudo apt-get update;
    sudo apt-get install -y ansible;
    cd /NRMC2019;
    sudo ansible-playbook -v -i "localhost," -c local src/utilities/ansible/dev_computer_playbook.yml"
  - docker exec -u travis -t NRMC2019-CI bash -c "
    echo 'source /opt/ros/kinetic/setup.bash' >> ~/.bashrc"

script:
  - docker exec -u travis -t NRMC2019-CI bash -c "catkin_make"
  - docker exec -u travis -t NRMC2019-CI bash -c "rm -rf build devel"
  - docker exec -u travis -t NRMC2019-CI bash -c "catkin_make run_tests"