sudo: required

language: ruby

services:
- docker

before_install:
- docker pull ubuntu/xenial
- docker run -d -p 127.0.0.1:80:4567 ubuntu/xenial /bin/sh -c "
    mkdir test;
    ls;"
- docker ps -a
