sudo: required

language: python

services:
  - docker

before_install:
  - docker pull ubuntu:xenial
  - docker run -d --name NRMC2019-CI -v $(pwd):/NRMC2019 ubuntu:xenial tail -f /dev/null
  - docker ps

install:
  - docker exec -t NRMC2019-CI bash -c "
    apt-get update;
    apt-get install -y ansible;
    cd /NRMC2019;
    ansible-playbook -i "localhost," -c local src/utilities/ansible/dev_computer_playbook.yml"