# based off https://github.com/jalessio/ansible-role-ros
# run locally with "ansible-playbook -i "localhost," -c local dev_computer_playbook.yml"
---
- hosts: localhost
  tasks:
    - include: ros_init.yml

    - name: install ros packages
      become: yes
      apt: pkg=ros-kinetic-{{ item }} state=latest update_cache=true
      with_items:
        - desktop

    - include: common_tasks.yml

    - name: get and unpack vrep
      unarchive:
        src: http://coppeliarobotics.com/files/V-REP_PRO_EDU_V3_5_0_Linux.tar.gz
        dest: ~/NRMC2019
        copy: no

    - name: configure vrep
      become: yes
      shell: |
        mv ~/NRMC2019/V-REP_PRO_EDU_V3_5_0_Linux ~/NRMC2019/vrep
        ln ~/NRMC2019/devel/lib/libv_repExtNRMC2019Plugin.so ~/NRMC2019/vrep/
        rm ~/NRMC2019/V-REP_PRO_EDU_V3_5_0_Linux.tar.gz

      args:
        executable: /bin/bash
