# goal
uint8 control_state
navigation_msgs/BezierSegment[] path
---
# result
uint8 control_state
float64 progress  # [0-1]
float64 deviation
---
# feedback
uint8 control_state
float64 progress  # [0-1]
float64 deviation