set(_CATKIN_CURRENT_PACKAGE "pc2cm")
set(pc2cm_VERSION "0.0.0")
set(pc2cm_MAINTAINER "nrmc <nrmc@todo.todo>")
set(pc2cm_PACKAGE_FORMAT "1")
set(pc2cm_BUILD_DEPENDS "roscpp" "gmock" "std_msgs" "geometry_msgs" "visualization_msgs" "message_generation")
set(pc2cm_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs" "geometry_msgs" "visualization_msgs" "message_runtime")
set(pc2cm_BUILDTOOL_DEPENDS "catkin")
set(pc2cm_BUILDTOOL_EXPORT_DEPENDS )
set(pc2cm_EXEC_DEPENDS "roscpp" "std_msgs" "geometry_msgs" "visualization_msgs" "message_runtime")
set(pc2cm_RUN_DEPENDS "roscpp" "std_msgs" "geometry_msgs" "visualization_msgs" "message_runtime")
set(pc2cm_TEST_DEPENDS )
set(pc2cm_DOC_DEPENDS )
set(pc2cm_URL_WEBSITE "")
set(pc2cm_URL_BUGTRACKER "")
set(pc2cm_URL_REPOSITORY "")
set(pc2cm_DEPRECATED "")